name: Release build

on:
  push:
    branches:
      - main
      - feature/github_actions

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
    - name: Setup googletest
      uses: actions/checkout@v2
      with:
        repository: google/googletest
        path: googletest

    - run: cmake googletest/.
    - run: cmake --build googletest/. --config Release
    - run: cmake --install googletest/.

    #- name: Setup Google benchmark
    #  uses: actions/checkout@v2
    #  with:
    #    repository: google/benchmark
    #    path: googlebenchmark

    #- run: cmake googlebenchmark/.
    #- run: cmake --build googlebenchmark/. --config Release
    #- run: cmake --install googlebenchmark/.

    - uses: actions/checkout@v2
      with:
        submodules: true
  
    - run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DGTEST_ROOT="C:/Program Files (x86)/googletest-distribution/" -DGBENCHMARK_ROOT="c:/Program Files (x86)/benchmark/"
    - run: cmake --build . --config Release
    - run: cmake --build . --config Release --target RUN_TESTS
    - run: cmake --build . --config Release --target package

    - name: Create Windows Release
      id: create_windows_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: win_release_v${{ github.run_number }}
        release_name: Windows Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_windows_release.outputs.upload_url }}
        asset_path: ./ip_filter-0.0.${{ github.run_number }}-win64.ZIP
        asset_name: ip_filter-0.0.${{ github.run_number }}-win64.ZIP
        asset_content_type: application/zip

  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y && sudo apt-get install libgtest-dev -y
    - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
    - run: cmake --build . --config Release
    - run: cmake --build . --config Release --target test
    - run: cmake --build . --config Release --target package

    - name: Create Linux Release
      id: create_linux_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: linux_release_v${{ github.run_number }}
        release_name: Linux Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_linux_release.outputs.upload_url }}
        asset_path: ./ip_filter-0.0.${{ github.run_number }}-Linux.deb
        asset_name: ip_filter-0.0.${{ github.run_number }}-Linux.deb
        asset_content_type: application/vnd.debian.binary-package
